steps:
  - name: node
    entrypoint: npm
    args: ["install"]
  - name: node
    entrypoint: npm
    args: ["add", "firebase-tools"]
  - name: node
    entrypoint: npm
    args: ["build"]
    env:
      [
        "REACT_APP_GOOGLE_ANALYTICS_KEY=$_GOOGLE_ANALYTICS_KEY",
        "REACT_APP_BUILD=$BUILD_ID",
        "REACT_APP_VERSION=$npm_package_version",
        "REACT_APP_NAME=$npm_package_name",
      ]
  - name: node
    entrypoint: "./node_modules/.bin/firebase"
    args:
      [
        "deploy",
        "--project",
        "$PROJECT_ID",
        "--token",
        "$_TOKEN",
        "--only",
        "hosting:xtracart",
      ]
